00:00:00.004195 main     VirtualBox COM Server 7.0.12 r159484 win.amd64 (Oct 12 2023 19:53:29) release log
00:00:00.004197 main     Log opened 2024-11-30T14:14:00.312602500Z
00:00:00.004197 main     Build Type: release
00:00:00.004203 main     OS Product: Windows 11
00:00:00.004204 main     OS Release: 10.0.22631
00:00:00.004204 main     OS Service Pack: 
00:00:00.026888 main     DMI Product Name: Nitro AN515-52
00:00:00.039703 main     DMI Product Version: V1.28
00:00:00.039719 main     Firmware type: UEFI
00:00:00.040116 main     Secure Boot: VERR_PRIVILEGE_NOT_HELD
00:00:00.040141 main     Host RAM: 8032MB (7.8GB) total, 1789MB available
00:00:00.040144 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
00:00:00.040145 main     Process ID: 25748
00:00:00.040145 main     Package type: WINDOWS_64BITS_GENERIC
00:00:00.150689          VirtualBox: object creation starts
00:00:00.150878          Home directory: 'C:\Users\Asilbek\.VirtualBox'
00:00:00.150977          Installed Drivers:
00:00:00.157851            C:\Windows\system32\DRIVERS\VBoxSup.sys (Version: 7.0.12.9484)
00:00:00.158332            C:\Windows\system32\DRIVERS\VBoxUSBMon.sys (Version: 7.0.12.9484)
00:00:00.158834            C:\Windows\system32\DRIVERS\VBoxNetAdp6.sys (Version: 7.0.12.9484)
00:00:00.159273            C:\Windows\system32\DRIVERS\VBoxNetLwf.sys (Version: 7.0.12.9484)
00:00:00.168691          Loading settings file "C:\Users\Asilbek\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.172409          usbLibGetDevices: Starting USB device enumeration
00:00:00.173514          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:00:00.173602          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 14
00:00:00.175452          usbLibGetDevices: Found 3 USB devices, 0 captured
00:00:00.175491          USB: Unknown USB device detected (idVendor: 0x0408, idProduct: 0xa060)
00:00:00.175523          USB: Unknown USB device detected (idVendor: 0x1ea7, idProduct: 0x0066)
00:00:00.175544          USB: Unknown USB device detected (idVendor: 0x8087, idProduct: 0x0aaa)
00:00:00.283302          HostDnsMonitor: initializing
00:00:00.292758          HostDnsMonitor: updating information
00:00:00.292782          HostDnsMonitor: old information
00:00:00.292783            no server entries
00:00:00.292784            no domain set
00:00:00.292784            no search string entries
00:00:00.292785          HostDnsMonitor: new information
00:00:00.292785            server 1: 192.168.43.1
00:00:00.292786            no domain set
00:00:00.292786            no search string entries
00:00:00.295015          VD: VDInit finished with VINF_SUCCESS
00:00:00.309541          Loading settings file "C:\Users\Asilbek\VirtualBox VMs\kali_linux_2022\kali_linux_2022.vbox" with version "1.19-windows"
00:00:00.322007          VirtualBox: object created
00:00:00.382675          Saving settings file "C:\Users\Asilbek\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.385488          Finished saving settings file "C:\Users\Asilbek\.VirtualBox\VirtualBox.xml"
00:00:00.385888          Saving settings file "C:\Users\Asilbek\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.389218          Finished saving settings file "C:\Users\Asilbek\.VirtualBox\VirtualBox.xml"
00:00:00.389455          Saving settings file "C:\Users\Asilbek\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.392303          Finished saving settings file "C:\Users\Asilbek\.VirtualBox\VirtualBox.xml"
00:00:01.217448          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={The machine is not mutable (state is Saved)}, preserve=false aResultDetail=0
00:00:03.618819          Launched VM: 3352555648 pid: 18600 (0x48a8) frontend: GUI/Qt name: kali_linux_2022
00:00:03.630991          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={The machine is not mutable (state is Saved)}, preserve=false aResultDetail=0
00:00:09.528117          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={The machine is not mutable (state is Saved)}, preserve=false aResultDetail=0
00:00:09.998082          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={70401eef-c8e9-466b-9660-45cb3e9979e4} aComponent={ExtPackManagerWrap} aText={No extension pack by the name 'Oracle VM VirtualBox Extension Pack' was found}, preserve=false aResultDetail=0
00:00:11.916940          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={The machine is not mutable (state is Restoring)}, preserve=false aResultDetail=0
00:00:11.986290          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={SessionMachine} aText={The machine is not mutable or saved (state is Restoring)}, preserve=false aResultDetail=0
00:00:13.290760          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Property 'CRYPT/KeyId' does not exist}, preserve=false aResultDetail=0
00:00:20.469894          Saving settings file "C:\Users\Asilbek\VirtualBox VMs\kali_linux_2022\kali_linux_2022.vbox" with version "1.19-windows"
00:00:20.473834          Finished saving settings file "C:\Users\Asilbek\VirtualBox VMs\kali_linux_2022\kali_linux_2022.vbox"
00:00:20.567069          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={The machine is not mutable (state is Running)}, preserve=false aResultDetail=0
00:01:27.882055 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:01:27.883374 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:01:27.883525 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 14
00:01:27.883785 USBPROXY usbLibGetDevices: Found 3 USB devices, 0 captured
00:13:11.345084 dns-monitor HostDnsMonitor: updating information
00:13:11.345116 dns-monitor HostDnsMonitor: unchanged
00:13:25.636102 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:13:25.637189 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:13:25.637300 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 14
00:13:25.637514 USBPROXY usbLibGetDevices: Found 3 USB devices, 0 captured
00:13:28.967891 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:13:28.969092 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:13:28.969210 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 14
00:13:28.969407 USBPROXY usbLibGetDevices: Found 3 USB devices, 0 captured
00:13:29.563143 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:13:29.565090 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:13:29.565496 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 14
00:13:29.566128 USBPROXY usbLibGetDevices: Found 3 USB devices, 0 captured
00:13:34.588551 dns-monitor HostDnsMonitor: updating information
00:13:34.588568 dns-monitor HostDnsMonitor: unchanged
00:15:18.949712 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:15:18.955446 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:15:18.955613 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&8670eb8&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 14
00:15:18.955894 USBPROXY usbLibGetDevices: Found 3 USB devices, 0 captured
00:30:20.568643          Saving settings file "C:\Users\Asilbek\VirtualBox VMs\kali_linux_2022\kali_linux_2022.vbox" with version "1.19-windows"
00:30:20.576665          Finished saving settings file "C:\Users\Asilbek\VirtualBox VMs\kali_linux_2022\kali_linux_2022.vbox"
00:30:20.602720 SaveState Saving settings file "C:\Users\Asilbek\VirtualBox VMs\kali_linux_2022\kali_linux_2022.vbox" with version "1.19-windows"
00:30:20.608532 SaveState Finished saving settings file "C:\Users\Asilbek\VirtualBox VMs\kali_linux_2022\kali_linux_2022.vbox"
00:30:26.622099 main     VirtualBox: object deletion starts
00:30:26.623693 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\Asilbek\VirtualBox VMs\kali_linux_2022\kali_linux_2022.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
00:30:26.633421 main     HostDnsMonitor: shutting down ...
00:30:26.634109 main     HostDnsMonitor: shut down
00:30:26.646683 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={7682d5eb-f00e-44f1-8ca2-99d08b1cd607} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
00:30:26.648581 main     VirtualBox: object deleted
